/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AddFieldsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddFieldsDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddFieldsData
        //private AddFieldsData instance;

        public AddFieldsDataTests()
        {
            // TODO uncomment below to create an instance of AddFieldsData
            //instance = new AddFieldsData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddFieldsData
        /// </summary>
        [Fact]
        public void AddFieldsDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddFieldsData
            //Assert.IsType<AddFieldsData>(instance);
        }

        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
    }
}
