/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CombinePdfsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CombinePdfsDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CombinePdfsData
        //private CombinePdfsData instance;

        public CombinePdfsDataTests()
        {
            // TODO uncomment below to create an instance of CombinePdfsData
            //instance = new CombinePdfsData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CombinePdfsData
        /// </summary>
        [Fact]
        public void CombinePdfsDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CombinePdfsData
            //Assert.IsType<CombinePdfsData>(instance);
        }

        /// <summary>
        /// Test the property 'DeleteCustomFiles'
        /// </summary>
        [Fact]
        public void DeleteCustomFilesTest()
        {
            // TODO unit test for the property 'DeleteCustomFiles'
        }

        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'SourcePdfs'
        /// </summary>
        [Fact]
        public void SourcePdfsTest()
        {
            // TODO unit test for the property 'SourcePdfs'
        }

        /// <summary>
        /// Test the property 'Test'
        /// </summary>
        [Fact]
        public void TestTest()
        {
            // TODO unit test for the property 'Test'
        }
    }
}
