/* 
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Api;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test
{
    /// <summary>
    ///  Class for testing CombinePdfsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CombinePdfsDataTests
    {
        // TODO uncomment below to declare an instance variable for CombinePdfsData
        //private CombinePdfsData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CombinePdfsData
            //instance = new CombinePdfsData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CombinePdfsData
        /// </summary>
        [Test]
        public void CombinePdfsDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CombinePdfsData
            //Assert.IsInstanceOfType<CombinePdfsData> (instance, "variable 'instance' is a CombinePdfsData");
        }


        /// <summary>
        /// Test the property 'Test'
        /// </summary>
        [Test]
        public void TestTest()
        {
            // TODO unit test for the property 'Test'
        }
        /// <summary>
        /// Test the property 'SourcePdfs'
        /// </summary>
        [Test]
        public void SourcePdfsTest()
        {
            // TODO unit test for the property 'SourcePdfs'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Test]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }
        /// <summary>
        /// Test the property 'DeleteCustomFiles'
        /// </summary>
        [Test]
        public void DeleteCustomFilesTest()
        {
            // TODO unit test for the property 'DeleteCustomFiles'
        }

    }

}
