/* 
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Api;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test
{
    /// <summary>
    ///  Class for testing CombinedSubmission
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CombinedSubmissionTests
    {
        // TODO uncomment below to declare an instance variable for CombinedSubmission
        //private CombinedSubmission instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CombinedSubmission
            //instance = new CombinedSubmission();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CombinedSubmission
        /// </summary>
        [Test]
        public void CombinedSubmissionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CombinedSubmission
            //Assert.IsInstanceOfType<CombinedSubmission> (instance, "variable 'instance' is a CombinedSubmission");
        }


        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Expired'
        /// </summary>
        [Test]
        public void ExpiredTest()
        {
            // TODO unit test for the property 'Expired'
        }
        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Test]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }
        /// <summary>
        /// Test the property 'SourcePdfs'
        /// </summary>
        [Test]
        public void SourcePdfsTest()
        {
            // TODO unit test for the property 'SourcePdfs'
        }
        /// <summary>
        /// Test the property 'PdfHash'
        /// </summary>
        [Test]
        public void PdfHashTest()
        {
            // TODO unit test for the property 'PdfHash'
        }
        /// <summary>
        /// Test the property 'DownloadUrl'
        /// </summary>
        [Test]
        public void DownloadUrlTest()
        {
            // TODO unit test for the property 'DownloadUrl'
        }
        /// <summary>
        /// Test the property 'SubmissionIds'
        /// </summary>
        [Test]
        public void SubmissionIdsTest()
        {
            // TODO unit test for the property 'SubmissionIds'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Test]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }

    }

}
