/*
 * DocSpring API
 *
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CombinedSubmissionData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CombinedSubmissionDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CombinedSubmissionData
        //private CombinedSubmissionData instance;

        public CombinedSubmissionDataTests()
        {
            // TODO uncomment below to create an instance of CombinedSubmissionData
            //instance = new CombinedSubmissionData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CombinedSubmissionData
        /// </summary>
        [Fact]
        public void CombinedSubmissionDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CombinedSubmissionData
            //Assert.IsType<CombinedSubmissionData>(instance);
        }

        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'SubmissionIds'
        /// </summary>
        [Fact]
        public void SubmissionIdsTest()
        {
            // TODO unit test for the property 'SubmissionIds'
        }

        /// <summary>
        /// Test the property 'Test'
        /// </summary>
        [Fact]
        public void TestTest()
        {
            // TODO unit test for the property 'Test'
        }
    }
}
