/* 
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Api;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test
{
    /// <summary>
    ///  Class for testing CreateSubmissionBatchSubmissionsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateSubmissionBatchSubmissionsResponseTests
    {
        // TODO uncomment below to declare an instance variable for CreateSubmissionBatchSubmissionsResponse
        //private CreateSubmissionBatchSubmissionsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateSubmissionBatchSubmissionsResponse
            //instance = new CreateSubmissionBatchSubmissionsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateSubmissionBatchSubmissionsResponse
        /// </summary>
        [Test]
        public void CreateSubmissionBatchSubmissionsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateSubmissionBatchSubmissionsResponse
            //Assert.IsInstanceOfType<CreateSubmissionBatchSubmissionsResponse> (instance, "variable 'instance' is a CreateSubmissionBatchSubmissionsResponse");
        }


        /// <summary>
        /// Test the property 'Submission'
        /// </summary>
        [Test]
        public void SubmissionTest()
        {
            // TODO unit test for the property 'Submission'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
