/* 
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Api;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test
{
    /// <summary>
    ///  Class for testing CreateTemplateFromUploadData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateTemplateFromUploadDataTests
    {
        // TODO uncomment below to declare an instance variable for CreateTemplateFromUploadData
        //private CreateTemplateFromUploadData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateTemplateFromUploadData
            //instance = new CreateTemplateFromUploadData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateTemplateFromUploadData
        /// </summary>
        [Test]
        public void CreateTemplateFromUploadDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateTemplateFromUploadData
            //Assert.IsInstanceOfType<CreateTemplateFromUploadData> (instance, "variable 'instance' is a CreateTemplateFromUploadData");
        }


        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }

    }

}
