/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CreateSubmissionData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateSubmissionDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateSubmissionData
        //private CreateSubmissionData instance;

        public CreateSubmissionDataTests()
        {
            // TODO uncomment below to create an instance of CreateSubmissionData
            //instance = new CreateSubmissionData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateSubmissionData
        /// </summary>
        [Fact]
        public void CreateSubmissionDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateSubmissionData
            //Assert.IsType<CreateSubmissionData>(instance);
        }

        /// <summary>
        /// Test the property 'Css'
        /// </summary>
        [Fact]
        public void CssTest()
        {
            // TODO unit test for the property 'Css'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'DataRequests'
        /// </summary>
        [Fact]
        public void DataRequestsTest()
        {
            // TODO unit test for the property 'DataRequests'
        }

        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }

        /// <summary>
        /// Test the property 'FieldOverrides'
        /// </summary>
        [Fact]
        public void FieldOverridesTest()
        {
            // TODO unit test for the property 'FieldOverrides'
        }

        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Fact]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'Test'
        /// </summary>
        [Fact]
        public void TestTest()
        {
            // TODO unit test for the property 'Test'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
