/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CreateSubmissionBatchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateSubmissionBatchResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateSubmissionBatchResponse
        //private CreateSubmissionBatchResponse instance;

        public CreateSubmissionBatchResponseTests()
        {
            // TODO uncomment below to create an instance of CreateSubmissionBatchResponse
            //instance = new CreateSubmissionBatchResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateSubmissionBatchResponse
        /// </summary>
        [Fact]
        public void CreateSubmissionBatchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateSubmissionBatchResponse
            //Assert.IsType<CreateSubmissionBatchResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

        /// <summary>
        /// Test the property 'SubmissionBatch'
        /// </summary>
        [Fact]
        public void SubmissionBatchTest()
        {
            // TODO unit test for the property 'SubmissionBatch'
        }

        /// <summary>
        /// Test the property 'Submissions'
        /// </summary>
        [Fact]
        public void SubmissionsTest()
        {
            // TODO unit test for the property 'Submissions'
        }
    }
}
