/*
 * DocSpring API
 *
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CreateHtmlSubmissionData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateHtmlSubmissionDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateHtmlSubmissionData
        //private CreateHtmlSubmissionData instance;

        public CreateHtmlSubmissionDataTests()
        {
            // TODO uncomment below to create an instance of CreateHtmlSubmissionData
            //instance = new CreateHtmlSubmissionData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateHtmlSubmissionData
        /// </summary>
        [Fact]
        public void CreateHtmlSubmissionDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateHtmlSubmissionData
            //Assert.IsType<CreateHtmlSubmissionData>(instance);
        }

        /// <summary>
        /// Test the property 'Css'
        /// </summary>
        [Fact]
        public void CssTest()
        {
            // TODO unit test for the property 'Css'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Editable'
        /// </summary>
        [Fact]
        public void EditableTest()
        {
            // TODO unit test for the property 'Editable'
        }

        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }

        /// <summary>
        /// Test the property 'FieldOverrides'
        /// </summary>
        [Fact]
        public void FieldOverridesTest()
        {
            // TODO unit test for the property 'FieldOverrides'
        }

        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Fact]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'Test'
        /// </summary>
        [Fact]
        public void TestTest()
        {
            // TODO unit test for the property 'Test'
        }
    }
}
