/* 
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Api;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test
{
    /// <summary>
    ///  Class for testing CreateHtmlTemplateData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateHtmlTemplateDataTests
    {
        // TODO uncomment below to declare an instance variable for CreateHtmlTemplateData
        //private CreateHtmlTemplateData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateHtmlTemplateData
            //instance = new CreateHtmlTemplateData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateHtmlTemplateData
        /// </summary>
        [Test]
        public void CreateHtmlTemplateDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateHtmlTemplateData
            //Assert.IsInstanceOfType<CreateHtmlTemplateData> (instance, "variable 'instance' is a CreateHtmlTemplateData");
        }


        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }

    }

}
