/*
 * DocSpring API
 *
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ListSubmissionsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListSubmissionsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListSubmissionsResponse
        //private ListSubmissionsResponse instance;

        public ListSubmissionsResponseTests()
        {
            // TODO uncomment below to create an instance of ListSubmissionsResponse
            //instance = new ListSubmissionsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListSubmissionsResponse
        /// </summary>
        [Fact]
        public void ListSubmissionsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListSubmissionsResponse
            //Assert.IsType<ListSubmissionsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Submissions'
        /// </summary>
        [Fact]
        public void SubmissionsTest()
        {
            // TODO unit test for the property 'Submissions'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

        /// <summary>
        /// Test the property 'NextCursor'
        /// </summary>
        [Fact]
        public void NextCursorTest()
        {
            // TODO unit test for the property 'NextCursor'
        }
    }
}
