/*
 * DocSpring API
 *
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing MoveFolderData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MoveFolderDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MoveFolderData
        //private MoveFolderData instance;

        public MoveFolderDataTests()
        {
            // TODO uncomment below to create an instance of MoveFolderData
            //instance = new MoveFolderData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MoveFolderData
        /// </summary>
        [Fact]
        public void MoveFolderDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" MoveFolderData
            //Assert.IsType<MoveFolderData>(instance);
        }

        /// <summary>
        /// Test the property 'ParentFolderId'
        /// </summary>
        [Fact]
        public void ParentFolderIdTest()
        {
            // TODO unit test for the property 'ParentFolderId'
        }
    }
}
