/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PublishTemplateVersionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublishTemplateVersionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PublishTemplateVersionResponse
        //private PublishTemplateVersionResponse instance;

        public PublishTemplateVersionResponseTests()
        {
            // TODO uncomment below to create an instance of PublishTemplateVersionResponse
            //instance = new PublishTemplateVersionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PublishTemplateVersionResponse
        /// </summary>
        [Fact]
        public void PublishTemplateVersionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PublishTemplateVersionResponse
            //Assert.IsType<PublishTemplateVersionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
    }
}
