/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RenameFolderData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RenameFolderDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RenameFolderData
        //private RenameFolderData instance;

        public RenameFolderDataTests()
        {
            // TODO uncomment below to create an instance of RenameFolderData
            //instance = new RenameFolderData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RenameFolderData
        /// </summary>
        [Fact]
        public void RenameFolderDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" RenameFolderData
            //Assert.IsType<RenameFolderData>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
