/* 
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Api;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test
{
    /// <summary>
    ///  Class for testing SubmissionData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmissionDataTests
    {
        // TODO uncomment below to declare an instance variable for SubmissionData
        //private SubmissionData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubmissionData
            //instance = new SubmissionData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubmissionData
        /// </summary>
        [Test]
        public void SubmissionDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubmissionData
            //Assert.IsInstanceOfType<SubmissionData> (instance, "variable 'instance' is a SubmissionData");
        }


        /// <summary>
        /// Test the property 'Test'
        /// </summary>
        [Test]
        public void TestTest()
        {
            // TODO unit test for the property 'Test'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Test]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }
        /// <summary>
        /// Test the property 'Css'
        /// </summary>
        [Test]
        public void CssTest()
        {
            // TODO unit test for the property 'Css'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'DataRequests'
        /// </summary>
        [Test]
        public void DataRequestsTest()
        {
            // TODO unit test for the property 'DataRequests'
        }

    }

}
