/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SubmissionData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubmissionDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubmissionData
        //private SubmissionData instance;

        public SubmissionDataTests()
        {
            // TODO uncomment below to create an instance of SubmissionData
            //instance = new SubmissionData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubmissionData
        /// </summary>
        [Fact]
        public void SubmissionDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubmissionData
            //Assert.IsType<SubmissionData>(instance);
        }

        /// <summary>
        /// Test the property 'Css'
        /// </summary>
        [Fact]
        public void CssTest()
        {
            // TODO unit test for the property 'Css'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'DataRequests'
        /// </summary>
        [Fact]
        public void DataRequestsTest()
        {
            // TODO unit test for the property 'DataRequests'
        }

        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Fact]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Test'
        /// </summary>
        [Fact]
        public void TestTest()
        {
            // TODO unit test for the property 'Test'
        }
    }
}
