/*
 * DocSpring API
 *
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SubmissionPreview
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubmissionPreviewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubmissionPreview
        //private SubmissionPreview instance;

        public SubmissionPreviewTests()
        {
            // TODO uncomment below to create an instance of SubmissionPreview
            //instance = new SubmissionPreview();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubmissionPreview
        /// </summary>
        [Fact]
        public void SubmissionPreviewInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubmissionPreview
            //Assert.IsType<SubmissionPreview>(instance);
        }

        /// <summary>
        /// Test the property 'BatchId'
        /// </summary>
        [Fact]
        public void BatchIdTest()
        {
            // TODO unit test for the property 'BatchId'
        }

        /// <summary>
        /// Test the property 'DataRequests'
        /// </summary>
        [Fact]
        public void DataRequestsTest()
        {
            // TODO unit test for the property 'DataRequests'
        }

        /// <summary>
        /// Test the property 'Editable'
        /// </summary>
        [Fact]
        public void EditableTest()
        {
            // TODO unit test for the property 'Editable'
        }

        /// <summary>
        /// Test the property 'Expired'
        /// </summary>
        [Fact]
        public void ExpiredTest()
        {
            // TODO unit test for the property 'Expired'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'JsonSchemaErrors'
        /// </summary>
        [Fact]
        public void JsonSchemaErrorsTest()
        {
            // TODO unit test for the property 'JsonSchemaErrors'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'ProcessedAt'
        /// </summary>
        [Fact]
        public void ProcessedAtTest()
        {
            // TODO unit test for the property 'ProcessedAt'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }

        /// <summary>
        /// Test the property 'TemplateType'
        /// </summary>
        [Fact]
        public void TemplateTypeTest()
        {
            // TODO unit test for the property 'TemplateType'
        }

        /// <summary>
        /// Test the property 'TemplateVersion'
        /// </summary>
        [Fact]
        public void TemplateVersionTest()
        {
            // TODO unit test for the property 'TemplateVersion'
        }

        /// <summary>
        /// Test the property 'Test'
        /// </summary>
        [Fact]
        public void TestTest()
        {
            // TODO unit test for the property 'Test'
        }

        /// <summary>
        /// Test the property 'TruncatedText'
        /// </summary>
        [Fact]
        public void TruncatedTextTest()
        {
            // TODO unit test for the property 'TruncatedText'
        }

        /// <summary>
        /// Test the property 'PdfHash'
        /// </summary>
        [Fact]
        public void PdfHashTest()
        {
            // TODO unit test for the property 'PdfHash'
        }

        /// <summary>
        /// Test the property 'DownloadUrl'
        /// </summary>
        [Fact]
        public void DownloadUrlTest()
        {
            // TODO unit test for the property 'DownloadUrl'
        }

        /// <summary>
        /// Test the property 'PermanentDownloadUrl'
        /// </summary>
        [Fact]
        public void PermanentDownloadUrlTest()
        {
            // TODO unit test for the property 'PermanentDownloadUrl'
        }

        /// <summary>
        /// Test the property 'PreviewDownloadUrl'
        /// </summary>
        [Fact]
        public void PreviewDownloadUrlTest()
        {
            // TODO unit test for the property 'PreviewDownloadUrl'
        }

        /// <summary>
        /// Test the property 'PreviewGeneratedAt'
        /// </summary>
        [Fact]
        public void PreviewGeneratedAtTest()
        {
            // TODO unit test for the property 'PreviewGeneratedAt'
        }

        /// <summary>
        /// Test the property 'AuditTrailDownloadUrl'
        /// </summary>
        [Fact]
        public void AuditTrailDownloadUrlTest()
        {
            // TODO unit test for the property 'AuditTrailDownloadUrl'
        }

        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Fact]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }
    }
}
