/*
 * DocSpring API
 *
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SubmissionBatchData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubmissionBatchDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubmissionBatchData
        //private SubmissionBatchData instance;

        public SubmissionBatchDataTests()
        {
            // TODO uncomment below to create an instance of SubmissionBatchData
            //instance = new SubmissionBatchData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubmissionBatchData
        /// </summary>
        [Fact]
        public void SubmissionBatchDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubmissionBatchData
            //Assert.IsType<SubmissionBatchData>(instance);
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Submissions'
        /// </summary>
        [Fact]
        public void SubmissionsTest()
        {
            // TODO unit test for the property 'Submissions'
        }

        /// <summary>
        /// Test the property 'Test'
        /// </summary>
        [Fact]
        public void TestTest()
        {
            // TODO unit test for the property 'Test'
        }
    }
}
