/*
 * DocSpring API
 *
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SubmissionBatchWithSubmissions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubmissionBatchWithSubmissionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubmissionBatchWithSubmissions
        //private SubmissionBatchWithSubmissions instance;

        public SubmissionBatchWithSubmissionsTests()
        {
            // TODO uncomment below to create an instance of SubmissionBatchWithSubmissions
            //instance = new SubmissionBatchWithSubmissions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubmissionBatchWithSubmissions
        /// </summary>
        [Fact]
        public void SubmissionBatchWithSubmissionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubmissionBatchWithSubmissions
            //Assert.IsType<SubmissionBatchWithSubmissions>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'ProcessedAt'
        /// </summary>
        [Fact]
        public void ProcessedAtTest()
        {
            // TODO unit test for the property 'ProcessedAt'
        }

        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

        /// <summary>
        /// Test the property 'PendingCount'
        /// </summary>
        [Fact]
        public void PendingCountTest()
        {
            // TODO unit test for the property 'PendingCount'
        }

        /// <summary>
        /// Test the property 'ErrorCount'
        /// </summary>
        [Fact]
        public void ErrorCountTest()
        {
            // TODO unit test for the property 'ErrorCount'
        }

        /// <summary>
        /// Test the property 'CompletionPercentage'
        /// </summary>
        [Fact]
        public void CompletionPercentageTest()
        {
            // TODO unit test for the property 'CompletionPercentage'
        }

        /// <summary>
        /// Test the property 'Submissions'
        /// </summary>
        [Fact]
        public void SubmissionsTest()
        {
            // TODO unit test for the property 'Submissions'
        }
    }
}
