/*
 * DocSpring API
 *
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SubmissionDataRequestEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubmissionDataRequestEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubmissionDataRequestEvent
        //private SubmissionDataRequestEvent instance;

        public SubmissionDataRequestEventTests()
        {
            // TODO uncomment below to create an instance of SubmissionDataRequestEvent
            //instance = new SubmissionDataRequestEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubmissionDataRequestEvent
        /// </summary>
        [Fact]
        public void SubmissionDataRequestEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubmissionDataRequestEvent
            //Assert.IsType<SubmissionDataRequestEvent>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'SubmissionId'
        /// </summary>
        [Fact]
        public void SubmissionIdTest()
        {
            // TODO unit test for the property 'SubmissionId'
        }

        /// <summary>
        /// Test the property 'SubmissionDataRequestId'
        /// </summary>
        [Fact]
        public void SubmissionDataRequestIdTest()
        {
            // TODO unit test for the property 'SubmissionDataRequestId'
        }

        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

        /// <summary>
        /// Test the property 'MessageType'
        /// </summary>
        [Fact]
        public void MessageTypeTest()
        {
            // TODO unit test for the property 'MessageType'
        }

        /// <summary>
        /// Test the property 'MessageRecipient'
        /// </summary>
        [Fact]
        public void MessageRecipientTest()
        {
            // TODO unit test for the property 'MessageRecipient'
        }

        /// <summary>
        /// Test the property 'OccurredAt'
        /// </summary>
        [Fact]
        public void OccurredAtTest()
        {
            // TODO unit test for the property 'OccurredAt'
        }
    }
}
