/* 
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Api;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test
{
    /// <summary>
    ///  Class for testing TemplatestemplateIdTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TemplatestemplateIdTemplateTests
    {
        // TODO uncomment below to declare an instance variable for TemplatestemplateIdTemplate
        //private TemplatestemplateIdTemplate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TemplatestemplateIdTemplate
            //instance = new TemplatestemplateIdTemplate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TemplatestemplateIdTemplate
        /// </summary>
        [Test]
        public void TemplatestemplateIdTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TemplatestemplateIdTemplate
            //Assert.IsInstanceOfType<TemplatestemplateIdTemplate> (instance, "variable 'instance' is a TemplatestemplateIdTemplate");
        }


        /// <summary>
        /// Test the property 'ExpirationInterval'
        /// </summary>
        [Test]
        public void ExpirationIntervalTest()
        {
            // TODO unit test for the property 'ExpirationInterval'
        }
        /// <summary>
        /// Test the property 'WebhookUrl'
        /// </summary>
        [Test]
        public void WebhookUrlTest()
        {
            // TODO unit test for the property 'WebhookUrl'
        }
        /// <summary>
        /// Test the property 'Scss'
        /// </summary>
        [Test]
        public void ScssTest()
        {
            // TODO unit test for the property 'Scss'
        }
        /// <summary>
        /// Test the property 'ExpireAfter'
        /// </summary>
        [Test]
        public void ExpireAfterTest()
        {
            // TODO unit test for the property 'ExpireAfter'
        }
        /// <summary>
        /// Test the property 'AllowAdditionalProperties'
        /// </summary>
        [Test]
        public void AllowAdditionalPropertiesTest()
        {
            // TODO unit test for the property 'AllowAdditionalProperties'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'PublicSubmissions'
        /// </summary>
        [Test]
        public void PublicSubmissionsTest()
        {
            // TODO unit test for the property 'PublicSubmissions'
        }
        /// <summary>
        /// Test the property 'SlackWebhookUrl'
        /// </summary>
        [Test]
        public void SlackWebhookUrlTest()
        {
            // TODO unit test for the property 'SlackWebhookUrl'
        }
        /// <summary>
        /// Test the property 'HeaderHtml'
        /// </summary>
        [Test]
        public void HeaderHtmlTest()
        {
            // TODO unit test for the property 'HeaderHtml'
        }
        /// <summary>
        /// Test the property 'PublicWebForm'
        /// </summary>
        [Test]
        public void PublicWebFormTest()
        {
            // TODO unit test for the property 'PublicWebForm'
        }
        /// <summary>
        /// Test the property 'EditableSubmissions'
        /// </summary>
        [Test]
        public void EditableSubmissionsTest()
        {
            // TODO unit test for the property 'EditableSubmissions'
        }
        /// <summary>
        /// Test the property 'ExpireSubmissions'
        /// </summary>
        [Test]
        public void ExpireSubmissionsTest()
        {
            // TODO unit test for the property 'ExpireSubmissions'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Test]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }
        /// <summary>
        /// Test the property 'FooterHtml'
        /// </summary>
        [Test]
        public void FooterHtmlTest()
        {
            // TODO unit test for the property 'FooterHtml'
        }
        /// <summary>
        /// Test the property 'RedirectUrl'
        /// </summary>
        [Test]
        public void RedirectUrlTest()
        {
            // TODO unit test for the property 'RedirectUrl'
        }

    }

}
