/* 
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Api;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test
{
    /// <summary>
    ///  Class for testing TemplatesdesccachedUploadTemplateDocumentMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TemplatesdesccachedUploadTemplateDocumentMetadataTests
    {
        // TODO uncomment below to declare an instance variable for TemplatesdesccachedUploadTemplateDocumentMetadata
        //private TemplatesdesccachedUploadTemplateDocumentMetadata instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TemplatesdesccachedUploadTemplateDocumentMetadata
            //instance = new TemplatesdesccachedUploadTemplateDocumentMetadata();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TemplatesdesccachedUploadTemplateDocumentMetadata
        /// </summary>
        [Test]
        public void TemplatesdesccachedUploadTemplateDocumentMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TemplatesdesccachedUploadTemplateDocumentMetadata
            //Assert.IsInstanceOfType<TemplatesdesccachedUploadTemplateDocumentMetadata> (instance, "variable 'instance' is a TemplatesdesccachedUploadTemplateDocumentMetadata");
        }


        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Test]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Test]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }

    }

}
