/*
 * DocSpring API
 *
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateAddFieldsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateAddFieldsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateAddFieldsResponse
        //private TemplateAddFieldsResponse instance;

        public TemplateAddFieldsResponseTests()
        {
            // TODO uncomment below to create an instance of TemplateAddFieldsResponse
            //instance = new TemplateAddFieldsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateAddFieldsResponse
        /// </summary>
        [Fact]
        public void TemplateAddFieldsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateAddFieldsResponse
            //Assert.IsType<TemplateAddFieldsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

        /// <summary>
        /// Test the property 'NewFieldIds'
        /// </summary>
        [Fact]
        public void NewFieldIdsTest()
        {
            // TODO unit test for the property 'NewFieldIds'
        }
    }
}
