/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateDocument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateDocumentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateDocument
        //private TemplateDocument instance;

        public TemplateDocumentTests()
        {
            // TODO uncomment below to create an instance of TemplateDocument
            //instance = new TemplateDocument();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateDocument
        /// </summary>
        [Fact]
        public void TemplateDocumentInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateDocument
            //Assert.IsType<TemplateDocument>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Storage'
        /// </summary>
        [Fact]
        public void StorageTest()
        {
            // TODO unit test for the property 'Storage'
        }
    }
}
