/*
 * DocSpring API
 *
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateDeleteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateDeleteResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateDeleteResponse
        //private TemplateDeleteResponse instance;

        public TemplateDeleteResponseTests()
        {
            // TODO uncomment below to create an instance of TemplateDeleteResponse
            //instance = new TemplateDeleteResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateDeleteResponse
        /// </summary>
        [Fact]
        public void TemplateDeleteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateDeleteResponse
            //Assert.IsType<TemplateDeleteResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

        /// <summary>
        /// Test the property 'LatestVersion'
        /// </summary>
        [Fact]
        public void LatestVersionTest()
        {
            // TODO unit test for the property 'LatestVersion'
        }

        /// <summary>
        /// Test the property 'Versions'
        /// </summary>
        [Fact]
        public void VersionsTest()
        {
            // TODO unit test for the property 'Versions'
        }
    }
}
