/*
 * API v1
 *
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocSpring.Client.Model;
using DocSpring.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DocSpring.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateDefaults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateDefaultsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateDefaults
        //private TemplateDefaults instance;

        public TemplateDefaultsTests()
        {
            // TODO uncomment below to create an instance of TemplateDefaults
            //instance = new TemplateDefaults();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateDefaults
        /// </summary>
        [Fact]
        public void TemplateDefaultsInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateDefaults
            //Assert.IsType<TemplateDefaults>(instance);
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }

        /// <summary>
        /// Test the property 'FontSize'
        /// </summary>
        [Fact]
        public void FontSizeTest()
        {
            // TODO unit test for the property 'FontSize'
        }

        /// <summary>
        /// Test the property 'Typeface'
        /// </summary>
        [Fact]
        public void TypefaceTest()
        {
            // TODO unit test for the property 'Typeface'
        }
    }
}
